fix(build): temporarily pin nightly version to 2022-02-08
versions as of 2022-02-09 cause compilation errors in a third-party
dependency of this kind:

```
error[E0308]: mismatched types
  --> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/cap-primitives-0.24.0/src/fs/via_parent/create_dir.rs:16:46
   |
16 |     let (dir, basename) = open_parent(start, &path)?;
   |                                              ^^^^^ expected struct `Path`, found opaque type
   |
  ::: $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/cap-primitives-0.24.0/src/rustix/fs/dir_utils.rs:67:48
   |
67 | pub(crate) fn strip_dir_suffix(path: &Path) -> impl Deref<Target = Path> + '_ {
   |                                                ------------------------------ the found opaque type
   |
   = note:   expected struct `Path`
           found opaque type `impl Deref<Target = Path>`
```

This commit should be reverted once the issue is fixed.

Signed-off-by: Roman Volosatovs <roman@profian.com>