fix(sev): retry SNP `Launcher::init`
If there is a CI storm, where a lot of VMs are started, `/dev/sev` is
sometimes busy:

```
Error: SNP Launcher init failed

Caused by:
    0: I/O Error
    1: Device or resource busy (os error 16)
```

Try to reopen before the CI process has to be rekicked.

Signed-off-by: Harald Hoyer <harald@profian.com>