Update reqwest to 0.10 to avoid transitive dependency vulnerability
Otherwise we will be downstream of a crate with a known vulnerability:

error: Vulnerable crates found!

ID:       RUSTSEC-2019-0034
Crate:    http
Version:  0.1.18
Date:     2019-11-16
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0034
Title:    HeaderMap::Drain API is unsound
Solution:  upgrade to >= 0.1.20

ID:       RUSTSEC-2019-0033
Crate:    http
Version:  0.1.18
Date:     2019-11-16
URL:      https://rustsec.org/advisories/RUSTSEC-2019-0033
Title:    Integer Overflow in HeaderMap::reserve() can cause Denial of Service
Solution:  upgrade to >= 0.1.20

It looks like the entire reqwest 0.9 series releases depend on the
vulnerable version of http, so bump reqwest to 0.10 which is not
downstream of the vulnerable crate (and by extension, neither are we).