fix(sgx): do not use rbx register in asm!()
error: invalid register rbx: rbx is used internally by LLVM and
cannot be used as an operand for inline asm

So, we pull in a newer `sgx` crate version, which has this fixed.

See:
rust-lang/rust#84658 (comment)

and:
https://github.com/rust-lang/rust/pull/84658/files#diff-d7283132d97a993fad4e2d491ac883dbce4e17fe248cdf37fa3f9334e2a5a115

Signed-off-by: Harald Hoyer <harald@redhat.com>