fix(sev): print user friendly attestation_bridge errors
```
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    Permission denied (os error 13)
attestation_bridge error: failed to deserialize expected certificate chain
```

Signed-off-by: Harald Hoyer <harald@redhat.com>