tests/bin: Fix a linking issue
A fix for:

  enarx/tests/bin/bind.c:31: undefined reference to `__stack_chk_fail'

Add -fno-stack-protector because it apparently is a place where ABI
differences etc. can easily break the compilation.

Closes: #1251
Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@iki.fi>