fix: rework on-disk signature file locking
Fixed a race condition in previous implemention and removed unnecessary allocations and type conversions.

Most importantly, this adds workaround to a deadlock, which occurs, for example,
when test is killed by ^C and the lock file persists on disk.
There is no (reasonably simple) way to handle this,
but some mitigations are added. E.g. here's an example "dirty" case:

```
cargo test -j 8 wasm -- --nocapture

<...>

running 11 tests
waiting for workload to start...
waiting for workload to start...
stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` already reacquired by another thread
possibly stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` removed (this is prone to a race condition)
stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` already reacquired by another thread
stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` already reacquired by another thread
stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` already reacquired by another thread
stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` already reacquired by another thread
stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` already reacquired by another thread
possibly stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` removed (this is prone to a race condition)
possibly stale lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock` removed (this is prone to a race condition)
generated signature file `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.json`
generated signature file `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.json`
failed to remove lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock`: No such file or directory (os error 2)
generated signature file `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.json`
failed to remove lock at `/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/build/enarx-a1e1b6f3087bb2b9/out/sig.lock`: No such file or directory (os error 2)
Error: failed to get default function

Caused by:
    default export in '' is not a function
test wasm::no_export ... ok
test wasm::hello_wasi_snapshot1 ... ok
test wasm::return_1 ... ok
test wasm::wasi_snapshot1 ... ok
test wasm::memspike ... ok
test wasm::memory_stress_test ... ok
test wasm::echo ... ok
test wasm::listen_tls ... ok
test wasm::connect_tcp ... ok
test wasm::listen_tcp ... ok
test wasm::zerooneone ... ok

test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 25 filtered out; finished in 57.81s
```

Signed-off-by: Roman Volosatovs <roman@profian.com>