Makefile.toml: set RUST_RECURSION_COUNT = 0
`rustup` keeps track of recursion via the `RUST_RECURSION_COUNT`
environment variable.

Since `cargo make` uses up one increment, a chain of
- `cargo clippy`
 -> `cargo check`
  -> `rustc -vV`
   -> ...

Uses up to `rustup::env_var::RUST_RECURSION_COUNT_MAX` and we get the
error message:
```
[cargo-make][2] INFO - Running Task: clippy
[cargo-make][2] INFO - Execute Command: "cargo" "clippy"
error: process didn't exit successfully: `rustc -vV` (exit code: 1)
--- stderr
error: infinite recursion detected
```