ci: fix toolchain
```
Run actions-rs/toolchain@v1
/runner/_work/_temp/5a8c1328-61cf-4c6e-8a44-0a2477ad5648 --default-toolchain none -y
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: skipping toolchain installation
Rust is installed now. Great!
To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).
To configure your current shell, run:
source "$HOME/.cargo/env"
/root/.cargo/bin/rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup
installed toolchains
--------------------
error: no default toolchain configured
Error: The process '/root/.cargo/bin/rustup' failed with exit code 1
```

Signed-off-by: Harald Hoyer <harald@profian.com>