feat(backend/sev): add context message to `sev::cached_chain::get()?`
```
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`

Caused by:
    Permission denied (os error 13)
```

Signed-off-by: Harald Hoyer <harald@redhat.com>