Make rustfmt and clippy non-nightly
Using nightly rustfmt will cause CI errors all the time, when rustfmt
changes.

Also all components should build with stable by default and only
selected components should switch to nightly.

Additionally the `--channel=nightly` argument for `rustup.sh` did not
work for me.

```console
error: error: Found argument '--channel' which wasn't expected, or isn't valid in this context
```