fix: account for Rust compiler bug
When importing the crate externally, linking fails with:
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/shim_sgx-c8b5448528ac08f6.21hfef0kiee0n3z3.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/shim_sgx-c8b5448528ac08f6.59kg4uer0cwv1paj.rcgu.o" "-Wl,--as-needed" "-L" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps" "-L" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/debug/deps" "-L" "/nix/store/lqayfnl0slr4c9z1apa1nglcgvhwy1hh-rust-nightly-2022-02-22/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libnoted-ccb1c4c0e093517c.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libshim_sgx-5f4ba5b32f9a65a8.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/intern                               al/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libspinning-2ff421fe548fa6a6.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/liblock_api-2148e323f5d4fbc7.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libscopeguard-cd400e9c56e7c537.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libprimordial-70e78d5c179c022f.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libsgx-39504262cdefdebf.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libxsave-a56d092f99396e79.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libconst_default-731af71706aafbf0.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libx86_64-9f9b7d4d82139f2f.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libvolatile-542987f9bb3e7c09.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libbitflags-e39f434fcb7f9811.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libbit_field-085ba267d31cc0d2.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libsallyport-d7918a232a55e566.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/liblibc-923aa25ca71d5f48.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libgoblin-4df96a7ce7458ad7.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libscroll-f17be9964172dfca.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libcrt0stack-297520badc8bb401.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/librcrt1-7361366154bcaf41.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libgoblin-e966c9615f6aabc7.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libplain-4751d24cdcce7905.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libscroll-c452a19b33325e67.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libcompiler_builtins-23af07ffa2c63bd2.rlib" "/nix/store/9w2c7xbj6dr5wrikz60k1wzd1fxdvg0w-rust-std-nightly-2022-02-22-2022-02-22/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-d23d1fdf2f9c2e82.rlib" "/nix/store/9w2c7xbj6dr5wrikz60k1wzd1fxdvg0w-rust-std-nightly-2022-02-22-2022-02-22/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-4927c240c984c2ab.rlib" "/nix/store/9w2c7xbj6dr5wrikz60k1wzd1fxdvg0w-rust-std-nightly-2022-02-22-2022-02-22/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-9a4f50a9240e642d.rlib" "-Wl,-Bdynamic" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/nix/store/lqayfnl0slr4c9z1apa1nglcgvhwy1hh-rust-nightly-2022-02-22/lib/rustlib/x86_64-unknown-linux-musl/lib" "-o" "/home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/shim_sgx-c8b5448528ac08f6" "-Wl,--gc-sections" "-static-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs" "-Wl,--sort-section=alignment,-Tlayout.ld" "-nostartfiles"
  = note: /nix/store/sga0l55gm9nlwglk79lmihwb2bpv597j-binutils-2.35.2/bin/ld: /home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libshim_sgx-5f4ba5b32f9a65a8.rlib(shim_sgx-5f4ba5b32f9a65a8.4bvhvf00zm0tb5xw.rcgu.o): in function `sallyport::guest::call::enarxcall::alloc::<impl sallyport::guest::call::alloc::Alloc<sallyport::guest::call::alloc::kind::Enarxcall> for T>::stage':
          /home/rvolosatovs/src/github.com/enarx/sallyport/src/guest/call/enarxcall/alloc.rs:70: undefined reference to `<sallyport::guest::alloc::phase_alloc::Alloc<sallyport::guest::alloc::phase_alloc::phase::Stage> as sallyport::guest::alloc::Allocator>::section'
          /nix/store/sga0l55gm9nlwglk79lmihwb2bpv597j-binutils-2.35.2/bin/ld: /home/rvolosatovs/src/github.com/enarx/sallyport/src/guest/call/enarxcall/alloc.rs:70: undefined reference to `<core::result::Result<T,E> as core::ops::try_trait::Try>::branch'
          /nix/store/sga0l55gm9nlwglk79lmihwb2bpv597j-binutils-2.35.2/bin/ld: /home/rvolosatovs/src/github.com/enarx/enarx/internal/shim-sgx/target/x86_64-unknown-linux-musl/debug/deps/libshim_sgx-5f4ba5b32f9a65a8.rlib(shim_sgx-5f4ba5b32f9a65a8.xja46jvh106e9vh.rcgu.o): in function `<sallyport::guest::call::enarxcall::types::alloc::StagedAlloc<T> as sallyport::guest::alloc::Commit>::commit':
          /home/rvolosatovs/src/github.com/enarx/sallyport/src/guest/call/enarxcall/types/alloc.rs:25: undefined reference to `<sallyport::guest::alloc::output::Output<T,U> as sallyport::guest::alloc::Commit>::commit'
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

This commit fixes the issue. Revert once the compiler issue if fixed.

Signed-off-by: Roman Volosatovs <roman@profian.com>